;//==============================================================================================//
;//===========================================//PIO//============================================//
;//==============================================================================================//

[env:esp32dev]                                   ; Configuracao para o ESP32 DevKit
platform = espressif32@~6.7.0                    ; Plataforma ESP32, versao ~6.7.0
board = esp32dev                                 ; Placa de desenvolvimento ESP32
framework = arduino                              ; Usa o framework Arduino
monitor_speed = 115200                           ; Baud rate do monitor serial
monitor_filters = esp32_exception_decoder        ; Indica qual funcao e linha esta com erro

;//==============================================================================================//
;//==========================================//UPLOAD//==========================================//
;//==============================================================================================//

upload_protocol = esptool                        ; Flag para upload via UART

; Flags para upload via OTA
; upload_protocol = espota
; upload_port = 192.168.48.67
; upload_flags = 
; 	--host_port=45678
; 	--timeout=180

;//==============================================================================================//
;//===========================================//BUILD//==========================================//
;//==============================================================================================//

; board_build.partitions = huge_app.csv          ; Layout da flash para app grande

build_flags =                                    ; Flags que configuram a compilacao
	-O2                                          ; Otimiza codigo para desempenho
	-Wno-cpp                                     ; Desativa avisos pre-processador
	-Wno-pragmas                                 ; Desativa avisos de pragmas
	-ffunction-sections                          ; Funcoes em secoes separadas
	-fdata-sections                              ; Dados em secoes separadas
	-Wl,--gc-sections                            ; Remove codigo e dados nao usados
	-DLED_BUILTIN=2                              ; Define pino do LED integrado
	-DCORE_DEBUG_LEVEL=1                         ; Nivel de debug do core ESP32

lib_deps =                                       ; Bibliotecas usadas pelo codigo
	z3t0/IRremote@4.4.1                          ; Para controle remoto de TV
	fastled/FastLED@^3.5.0                       ; Para LEDs enderecaveis

lib_ldf_mode = deep+                             ; Busca profunda de dependencias

;//==============================================================================================//